#!/usr/bin/env bun
/**
 * Regenerates the ABI modules in `packages/abi/src` from the Foundry build artifacts
 * in `packages/contracts/out`.
 *
 *   bun run abi:sync          # == bun run scripts/sync-abi.ts
 *
 * The artifacts only exist after `bun run contracts:build`, which in turn needs the
 * exercise implementation contract. While it is missing, this script warns and exits 0
 * so the hand-written ABI that ships with the repo stays untouched.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

type AbiTarget = {
  /** Path of the artifact relative to `packages/contracts/out`. */
  readonly artifact: string;
  /** File name written under `packages/abi/src`. */
  readonly out: string;
  readonly exportName: string;
  readonly typeName: string;
};

const targets: readonly AbiTarget[] = [
  {
    artifact: "CoffeeTipJar.sol/CoffeeTipJar.json",
    out: "coffee-tip-jar.ts",
    exportName: "coffeeTipJarAbi",
    typeName: "CoffeeTipJarAbi",
  },
];

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const artifactsDir = join(repoRoot, "packages", "contracts", "out");
const abiSourceDir = join(repoRoot, "packages", "abi", "src");

const label = "abi:sync";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isNotFound(error: unknown): boolean {
  return isRecord(error) && error.code === "ENOENT";
}

function extractAbi(artifact: unknown): readonly unknown[] | undefined {
  if (!isRecord(artifact)) return undefined;
  const abi: unknown = artifact.abi;
  if (!Array.isArray(abi)) return undefined;
  const entries: readonly unknown[] = abi;
  return entries;
}

function renderModule(target: AbiTarget, abi: readonly unknown[]): string {
  return [
    `// AUTO-GENERATED by scripts/sync-abi.ts — do not edit by hand.`,
    `// Source: packages/contracts/out/${target.artifact}`,
    `// Regenerate with \`bun run abi:sync\` after \`bun run contracts:build\`,`,
    `// then \`bun run format\` to normalise the formatting.`,
    "",
    `export const ${target.exportName} = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
    `export type ${target.typeName} = typeof ${target.exportName};`,
    "",
  ].join("\n");
}

async function readFileOrUndefined(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNotFound(error)) return undefined;
    throw error;
  }
}

async function main(): Promise<void> {
  const missing: string[] = [];
  let written = 0;

  for (const target of targets) {
    const artifactPath = join(artifactsDir, target.artifact);
    const raw = await readFileOrUndefined(artifactPath);
    if (raw === undefined) {
      missing.push(target.artifact);
      continue;
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      throw new Error(`Artifact packages/contracts/out/${target.artifact} is not valid JSON.`);
    }

    const abi = extractAbi(parsed);
    if (abi === undefined) {
      throw new Error(`Artifact packages/contracts/out/${target.artifact} has no "abi" array.`);
    }

    await writeFile(join(abiSourceDir, target.out), renderModule(target, abi), "utf8");
    written += 1;
    console.log(`${label}  ${target.artifact} -> packages/abi/src/${target.out}`);
  }

  if (missing.length > 0) {
    console.warn(`${label}  WARNING: no Foundry artifact for: ${missing.join(", ")}`);
    console.warn(`${label}  Run \`bun run contracts:build\` first.`);
    console.warn(`${label}  If the exercise contract is not implemented yet this is expected —`);
    console.warn(`${label}  the hand-written ABI in packages/abi/src is left as it is.`);
  }

  if (written === 0) {
    console.log(`${label}  nothing to do.`);
  }
}

try {
  await main();
} catch (error) {
  console.error(`${label}  failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
}
